# Generated by Django 5.0.6 on 2024-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='total_files',
            field=models.IntegerField(max_length=99),
        ),
    ]
