# Generated by Django 5.0.6 on 2024-06-09 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_upload_total_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='total_files',
            field=models.IntegerField(),
        ),
    ]
