import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../App.css';
import '../index.css';
import { ToastContainer } from 'react-toastify';
import { CustomThemeProvider } from '@/context/ThemeContext/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'File Sharer',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomThemeProvider>
          {children} <ToastContainer />
        </CustomThemeProvider>
      </body>
    </html>
  );
}
