name: P2P MCP App Checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  run-app-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: app/package-lock.json
      - name: npm clean install
        run: npm ci --legacy-peer-deps
        shell: bash
        working-directory: ./app
      - name: Run linter
        run: npm run lint
        shell: bash
        working-directory: ./app
      - name: Build app
        run: npm run build
        shell: bash
        working-directory: ./app
      - name: Build MCP module
        run: npm run build:mcp-module
        shell: bash
        working-directory: ./app
